-- MySQL Script generated by MySQL Workbench
-- Sun Aug 19 16:47:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dependencia` ;

CREATE TABLE IF NOT EXISTS `Dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `nombreDependencia` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idDependencia`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreDependencia_UNIQUE` ON `Dependencia` (`nombreDependencia` ASC);


-- -----------------------------------------------------
-- Table `CargoEmpleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CargoEmpleado` ;

CREATE TABLE IF NOT EXISTS `CargoEmpleado` (
  `idCargoEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombreCargoEmpleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargoEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleado` ;

CREATE TABLE IF NOT EXISTS `Empleado` (
  `numEmpleado` INT NOT NULL,
  `nombresEmpleado` VARCHAR(40) NOT NULL,
  `apellidosEmpleado` VARCHAR(40) NOT NULL,
  `activo` TINYINT NOT NULL,
  `idCargo` INT NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`numEmpleado`),
  CONSTRAINT `Empleado_idCargo_FK`
    FOREIGN KEY (`idCargo`)
    REFERENCES `CargoEmpleado` (`idCargoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Empleado_idCargo_FK_idx` ON `Empleado` (`idCargo` ASC);


-- -----------------------------------------------------
-- Table `EstadoExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EstadoExpediente` ;

CREATE TABLE IF NOT EXISTS `EstadoExpediente` (
  `idEstadoExpediente` INT NOT NULL AUTO_INCREMENT,
  `nombreEstadoExpediente` VARCHAR(45) NOT NULL,
  `descripciónEstadoExpedientecol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEstadoExpediente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreEstadoExpediente_UNIQUE` ON `EstadoExpediente` (`nombreEstadoExpediente` ASC);


-- -----------------------------------------------------
-- Table `TipoDictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoDictamen` ;

CREATE TABLE IF NOT EXISTS `TipoDictamen` (
  `idTipoDictamen` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoDictamencol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDictamen`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreTipoDictamencol_UNIQUE` ON `TipoDictamen` (`nombreTipoDictamencol` ASC);


-- -----------------------------------------------------
-- Table `Dictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dictamen` ;

CREATE TABLE IF NOT EXISTS `Dictamen` (
  `idDictamen` INT NOT NULL AUTO_INCREMENT,
  `numDictamen` VARCHAR(25) NOT NULL,
  `idTipoDictamen` INT NOT NULL,
  PRIMARY KEY (`idDictamen`),
  CONSTRAINT `Dictamen_idTipoDictamen_FK`
    FOREIGN KEY (`idTipoDictamen`)
    REFERENCES `TipoDictamen` (`idTipoDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Dictamen_idTipoDictamen_FK_idx` ON `Dictamen` (`idTipoDictamen` ASC);

CREATE UNIQUE INDEX `numDictamen_UNIQUE` ON `Dictamen` (`numDictamen` ASC);


-- -----------------------------------------------------
-- Table `Asunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asunto` ;

CREATE TABLE IF NOT EXISTS `Asunto` (
  `idAsunto` INT NOT NULL AUTO_INCREMENT,
  `nombreAsunto` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(150) NULL,
  PRIMARY KEY (`idAsunto`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreTipoExpediente_UNIQUE` ON `Asunto` (`nombreAsunto` ASC);


-- -----------------------------------------------------
-- Table `FichaEntradaExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaExpediente` (
  `idFichaEntradaExpediente` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `interesado` VARCHAR(45) NOT NULL,
  `idAsunto` INT NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignación` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `idDependenciaRemision` INT NULL,
  `fechaRemision` DATETIME NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idEstadoExpediente` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaExpediente`),
  CONSTRAINT `FEE_iProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idDependencia_FK`
    FOREIGN KEY (`idDependenciaRemision`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idEstadoExpediente_FK`
    FOREIGN KEY (`idEstadoExpediente`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idAsunto_FK`
    FOREIGN KEY (`idAsunto`)
    REFERENCES `Asunto` (`idAsunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1256;

CREATE INDEX `FEE_iProcedencia_FK_idx` ON `FichaEntradaExpediente` (`idProcedencia` ASC);

CREATE INDEX `FEE_idEmpleadoReceptor_FK_idx` ON `FichaEntradaExpediente` (`idEmpleadoReceptor` ASC);

CREATE INDEX `FEE_idAbogadoAsignado_FK_idx` ON `FichaEntradaExpediente` (`idAbogadoAsignado` ASC);

CREATE INDEX `FEE_idDependencia_FK_idx` ON `FichaEntradaExpediente` (`idDependenciaRemision` ASC);

CREATE INDEX `FEE_idEstadoExpediente_FK_idx` ON `FichaEntradaExpediente` (`idEstadoExpediente` ASC);

CREATE INDEX `FEE_idDictamen_FK_idx` ON `FichaEntradaExpediente` (`idDictamen` ASC);

CREATE UNIQUE INDEX `idDictamen_UNIQUE` ON `FichaEntradaExpediente` (`idDictamen` ASC);

CREATE INDEX `FEE_idAsunto_FK_idx` ON `FichaEntradaExpediente` (`idAsunto` ASC);


-- -----------------------------------------------------
-- Table `Expediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Expediente` ;

CREATE TABLE IF NOT EXISTS `Expediente` (
  `idExpediente` INT NOT NULL AUTO_INCREMENT,
  `numExpediente` VARCHAR(20) NOT NULL,
  `folios` INT NOT NULL,
  PRIMARY KEY (`idExpediente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `numExpediente_UNIQUE` ON `Expediente` (`numExpediente` ASC);


-- -----------------------------------------------------
-- Table `RevisionExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RevisionExpediente` ;

CREATE TABLE IF NOT EXISTS `RevisionExpediente` (
  `idRevisionExpediente` INT NOT NULL AUTO_INCREMENT,
  `idFichaEntradaExpediente` INT NOT NULL,
  `idDependenciaRemison` INT NOT NULL,
  `fechaRemison` INT NOT NULL,
  `conDictamen` TINYINT NOT NULL,
  `idDependenciaRegreso` INT NULL,
  `fechaRegreso` DATETIME NULL,
  PRIMARY KEY (`idRevisionExpediente`),
  CONSTRAINT `RE_idFichaEntradaExpediente_FK`
    FOREIGN KEY (`idFichaEntradaExpediente`)
    REFERENCES `FichaEntradaExpediente` (`idFichaEntradaExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `RE_idDependenciaRemision_FK`
    FOREIGN KEY (`idDependenciaRemison`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RE_idDependenciaRegreso_FK`
    FOREIGN KEY (`idDependenciaRegreso`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `RE_idFichaEntradaExpediente_FK_idx` ON `RevisionExpediente` (`idFichaEntradaExpediente` ASC);

CREATE INDEX `RE_idDependenciaRemision_FK_idx` ON `RevisionExpediente` (`idDependenciaRemison` ASC);

CREATE INDEX `RE_idDependenciaRegreso_FK_idx` ON `RevisionExpediente` (`idDependenciaRegreso` ASC);


-- -----------------------------------------------------
-- Table `Folder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Folder` ;

CREATE TABLE IF NOT EXISTS `Folder` (
  `idFolder` INT NOT NULL AUTO_INCREMENT,
  `nombreFolder` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idFolder`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreFolder_UNIQUE` ON `Folder` (`nombreFolder` ASC);


-- -----------------------------------------------------
-- Table `Archivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archivo` ;

CREATE TABLE IF NOT EXISTS `Archivo` (
  `idDictamen` INT NOT NULL,
  `idFolder` INT NOT NULL,
  PRIMARY KEY (`idDictamen`, `idFolder`),
  CONSTRAINT `Archivo_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Archivo_idFolder_FK`
    FOREIGN KEY (`idFolder`)
    REFERENCES `Folder` (`idFolder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Archivo_idFolder_FK_idx` ON `Archivo` (`idFolder` ASC);


-- -----------------------------------------------------
-- Table `TipoLugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoLugar` ;

CREATE TABLE IF NOT EXISTS `TipoLugar` (
  `idTipoLugar` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoLugar` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idTipoLugar`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreTipoPatronato_UNIQUE` ON `TipoLugar` (`nombreTipoLugar` ASC);


-- -----------------------------------------------------
-- Table `FichaEntradaPatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaPatronato` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaPatronato` (
  `idFichaEntradaPatronato` INT NOT NULL AUTO_INCREMENT,
  `idTipoLugar` INT NOT NULL,
  `nombreColonia` VARCHAR(45) NOT NULL,
  `Asunto` VARCHAR(60) NOT NULL,
  `folios` INT NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `fechaRemision` DATETIME NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaPatronato`),
  CONSTRAINT `FEP_idTipoPatronato_FK`
    FOREIGN KEY (`idTipoLugar`)
    REFERENCES `TipoLugar` (`idTipoLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FEP_idTipoPatronato_FK_idx` ON `FichaEntradaPatronato` (`idTipoLugar` ASC);

CREATE INDEX `FEP_idEmpleadoReceptor_FK_idx` ON `FichaEntradaPatronato` (`idEmpleadoReceptor` ASC);

CREATE INDEX `FEP_idAbogadoAsignado_FK_idx` ON `FichaEntradaPatronato` (`idAbogadoAsignado` ASC);

CREATE INDEX `FEP_idDictamen_FK_idx` ON `FichaEntradaPatronato` (`idDictamen` ASC);

CREATE UNIQUE INDEX `idDictamen_UNIQUE` ON `FichaEntradaPatronato` (`idDictamen` ASC);


-- -----------------------------------------------------
-- Table `FichaEntradaOpinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaOpinion` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaOpinion` (
  `idFichaEntradaOpinion` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `idAsunto` INT NOT NULL,
  `numOficio` VARCHAR(30) NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `fechaRemision` DATETIME NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idEstadoOpinion` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaOpinion`),
  CONSTRAINT `FEO_idProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idEstadoOpinion_FK`
    FOREIGN KEY (`idEstadoOpinion`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idAsunto_FK`
    FOREIGN KEY (`idAsunto`)
    REFERENCES `Asunto` (`idAsunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FEO_idProcedencia_FK_idx` ON `FichaEntradaOpinion` (`idProcedencia` ASC);

CREATE INDEX `FEO_idEmpleadoReceptor_FK_idx` ON `FichaEntradaOpinion` (`idEmpleadoReceptor` ASC);

CREATE INDEX `FEO_idAbogadoAsignado_FK_idx` ON `FichaEntradaOpinion` (`idAbogadoAsignado` ASC);

CREATE INDEX `FEO_idEstadoOpinion_idx` ON `FichaEntradaOpinion` (`idEstadoOpinion` ASC);

CREATE INDEX `FEO_idDictamen_FK_idx` ON `FichaEntradaOpinion` (`idDictamen` ASC);

CREATE UNIQUE INDEX `idDictamen_UNIQUE` ON `FichaEntradaOpinion` (`idDictamen` ASC);

CREATE INDEX `FEO_idAsunto_FK_idx` ON `FichaEntradaOpinion` (`idAsunto` ASC);


-- -----------------------------------------------------
-- Table `FichaEntradaExpedienteXExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaExpedienteXExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaExpedienteXExpediente` (
  `idFichaEntradaExpediente` INT NOT NULL,
  `idExpediente` INT NOT NULL,
  PRIMARY KEY (`idFichaEntradaExpediente`, `idExpediente`),
  CONSTRAINT `FEEXE_idFichaEntradaExpediente_FK`
    FOREIGN KEY (`idFichaEntradaExpediente`)
    REFERENCES `FichaEntradaExpediente` (`idFichaEntradaExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FEEXE_idExpediente_FK`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `Expediente` (`idExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FEEXE_idExpediente_idx` ON `FichaEntradaExpedienteXExpediente` (`idExpediente` ASC);


-- -----------------------------------------------------
-- Table `PaginaDictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaginaDictamen` ;

CREATE TABLE IF NOT EXISTS `PaginaDictamen` (
  `idPaginaDictamen` INT NOT NULL AUTO_INCREMENT,
  `idDictamen` INT NOT NULL,
  `numeroPagina` INT NOT NULL,
  PRIMARY KEY (`idPaginaDictamen`),
  CONSTRAINT `PaginaDictamen_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `PaginaDictamen_idDictamen_FK_idx` ON `PaginaDictamen` (`idDictamen` ASC);


-- -----------------------------------------------------
-- Table `Privilegio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Privilegio` ;

CREATE TABLE IF NOT EXISTS `Privilegio` (
  `idPrivilegio` INT NOT NULL AUTO_INCREMENT,
  `nombrePrivilegio` VARCHAR(30) NOT NULL,
  `descripcionPrivilegio` VARCHAR(50) NULL,
  PRIMARY KEY (`idPrivilegio`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombrePrivilegio_UNIQUE` ON `Privilegio` (`nombrePrivilegio` ASC);


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `numEmpleado` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `Usuario_numEmpleado_FK`
    FOREIGN KEY (`numEmpleado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Usuariocol_UNIQUE` ON `Usuario` (`numEmpleado` ASC);


-- -----------------------------------------------------
-- Table `PrivilegioXUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PrivilegioXUsuario` ;

CREATE TABLE IF NOT EXISTS `PrivilegioXUsuario` (
  `idPrivilegio` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPrivilegio`, `idUsuario`),
  CONSTRAINT `PrivilegioXUsuario_idUsuario_FK`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PrivilegioXUsuario_idPrivilegio`
    FOREIGN KEY (`idPrivilegio`)
    REFERENCES `Privilegio` (`idPrivilegio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `PrivilegioXUsuario_idUsuario_FK_idx` ON `PrivilegioXUsuario` (`idUsuario` ASC);


-- -----------------------------------------------------
-- Table `ExpedientePatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExpedientePatronato` ;

CREATE TABLE IF NOT EXISTS `ExpedientePatronato` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
