-- MySQL Script generated by MySQL Workbench
-- Fri Feb  8 09:26:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dependencia` ;

CREATE TABLE IF NOT EXISTS `Dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `nombreDependencia` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idDependencia`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreDependencia_UNIQUE` ON `Dependencia` (`nombreDependencia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `CargoEmpleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CargoEmpleado` ;

CREATE TABLE IF NOT EXISTS `CargoEmpleado` (
  `idCargoEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombreCargoEmpleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargoEmpleado`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreCargoEmpleado_UNIQUE` ON `CargoEmpleado` (`nombreCargoEmpleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleado` ;

CREATE TABLE IF NOT EXISTS `Empleado` (
  `numEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpleado` VARCHAR(60) NOT NULL,
  `activo` TINYINT NOT NULL,
  `idCargo` INT NOT NULL,
  PRIMARY KEY (`numEmpleado`),
  CONSTRAINT `Empleado_idCargo_FK`
    FOREIGN KEY (`idCargo`)
    REFERENCES `CargoEmpleado` (`idCargoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `Empleado_idCargo_FK_idx` ON `Empleado` (`idCargo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EstadoExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EstadoExpediente` ;

CREATE TABLE IF NOT EXISTS `EstadoExpediente` (
  `idEstadoExpediente` INT NOT NULL AUTO_INCREMENT,
  `nombreEstadoExpediente` VARCHAR(45) NOT NULL,
  `descripcionEstadoExpediente` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`idEstadoExpediente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreEstadoExpediente_UNIQUE` ON `EstadoExpediente` (`nombreEstadoExpediente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TipoDictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoDictamen` ;

CREATE TABLE IF NOT EXISTS `TipoDictamen` (
  `idTipoDictamen` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoDictamen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDictamen`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreTipoDictamencol_UNIQUE` ON `TipoDictamen` (`nombreTipoDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Dictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dictamen` ;

CREATE TABLE IF NOT EXISTS `Dictamen` (
  `idDictamen` INT NOT NULL AUTO_INCREMENT,
  `numDictamen` VARCHAR(25) NOT NULL,
  `idTipoDictamen` INT NOT NULL,
  PRIMARY KEY (`idDictamen`),
  CONSTRAINT `Dictamen_idTipoDictamen_FK`
    FOREIGN KEY (`idTipoDictamen`)
    REFERENCES `TipoDictamen` (`idTipoDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Dictamen_idTipoDictamen_FK_idx` ON `Dictamen` (`idTipoDictamen` ASC) VISIBLE;

CREATE UNIQUE INDEX `numDictamen_UNIQUE` ON `Dictamen` (`numDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Asunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asunto` ;

CREATE TABLE IF NOT EXISTS `Asunto` (
  `idAsunto` INT NOT NULL AUTO_INCREMENT,
  `nombreAsunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAsunto`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreAsunto_UNIQUE` ON `Asunto` (`nombreAsunto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaExpediente` (
  `idFichaEntradaExpediente` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `interesado` VARCHAR(45) NOT NULL,
  `apoderadoLegal` VARCHAR(45) NULL,
  `idAsunto` INT NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `informacionAdicional` VARCHAR(200) NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATE NULL,
  `fechaDescargo` DATE NULL,
  `fechaRevision` DATE NULL,
  `idDependenciaRemision` INT NULL,
  `fechaRemision` DATE NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idEstadoExpediente` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaExpediente`),
  CONSTRAINT `FEE_iProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idDependencia_FK`
    FOREIGN KEY (`idDependenciaRemision`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idEstadoExpediente_FK`
    FOREIGN KEY (`idEstadoExpediente`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idAsunto_FK`
    FOREIGN KEY (`idAsunto`)
    REFERENCES `Asunto` (`idAsunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1256;

CREATE INDEX `FEE_iProcedencia_FK_idx` ON `FichaEntradaExpediente` (`idProcedencia` ASC) VISIBLE;

CREATE INDEX `FEE_idEmpleadoReceptor_FK_idx` ON `FichaEntradaExpediente` (`idEmpleadoReceptor` ASC) VISIBLE;

CREATE INDEX `FEE_idAbogadoAsignado_FK_idx` ON `FichaEntradaExpediente` (`idAbogadoAsignado` ASC) VISIBLE;

CREATE INDEX `FEE_idDependencia_FK_idx` ON `FichaEntradaExpediente` (`idDependenciaRemision` ASC) VISIBLE;

CREATE INDEX `FEE_idEstadoExpediente_FK_idx` ON `FichaEntradaExpediente` (`idEstadoExpediente` ASC) VISIBLE;

CREATE INDEX `FEE_idDictamen_FK_idx` ON `FichaEntradaExpediente` (`idDictamen` ASC) VISIBLE;

CREATE UNIQUE INDEX `idDictamen_UNIQUE` ON `FichaEntradaExpediente` (`idDictamen` ASC) VISIBLE;

CREATE INDEX `FEE_idAsunto_FK_idx` ON `FichaEntradaExpediente` (`idAsunto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Expediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Expediente` ;

CREATE TABLE IF NOT EXISTS `Expediente` (
  `idExpediente` INT NOT NULL AUTO_INCREMENT,
  `numExpediente` VARCHAR(30) NOT NULL,
  `folios` INT NOT NULL,
  PRIMARY KEY (`idExpediente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `numExpediente_UNIQUE` ON `Expediente` (`numExpediente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PrevisionExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PrevisionExpediente` ;

CREATE TABLE IF NOT EXISTS `PrevisionExpediente` (
  `idPrevisionExpediente` INT NOT NULL AUTO_INCREMENT,
  `idFichaEntradaExpediente` INT NOT NULL,
  `idDependenciaRemision` INT NOT NULL,
  `motivoRemision` VARCHAR(80) NULL,
  `recibidoPor` VARCHAR(45) NOT NULL,
  `fechaRemision` DATE NOT NULL,
  `idDependenciaRetorno` INT NULL,
  `idEmpleadoReceptor` INT NULL,
  `fechaRetorno` DATE NULL,
  PRIMARY KEY (`idPrevisionExpediente`),
  CONSTRAINT `PE_idFichaEntradaExpediente_FK`
    FOREIGN KEY (`idFichaEntradaExpediente`)
    REFERENCES `FichaEntradaExpediente` (`idFichaEntradaExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PE_idDependenciaRemision_FK`
    FOREIGN KEY (`idDependenciaRemision`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PE_idDependenciaRetorno_FK`
    FOREIGN KEY (`idDependenciaRetorno`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PE_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `RE_idFichaEntradaExpediente_FK_idx` ON `PrevisionExpediente` (`idFichaEntradaExpediente` ASC) VISIBLE;

CREATE INDEX `RE_idDependenciaRemision_FK_idx` ON `PrevisionExpediente` (`idDependenciaRemision` ASC) VISIBLE;

CREATE INDEX `RE_idDependenciaRegreso_FK_idx` ON `PrevisionExpediente` (`idDependenciaRetorno` ASC) VISIBLE;

CREATE INDEX `PE_idEmpleadoReceptor_FK_idx` ON `PrevisionExpediente` (`idEmpleadoReceptor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `AsuntoPatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AsuntoPatronato` ;

CREATE TABLE IF NOT EXISTS `AsuntoPatronato` (
  `idAsuntoPatronato` INT NOT NULL AUTO_INCREMENT,
  `nombreAsuntoPatronato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAsuntoPatronato`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreAsuntoPatronato_UNIQUE` ON `AsuntoPatronato` (`nombreAsuntoPatronato` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaPatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaPatronato` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaPatronato` (
  `idFichaEntradaPatronato` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `interesado` VARCHAR(45) NOT NULL,
  `apoderadoLegal` VARCHAR(45) NULL,
  `idAsuntoPatronato` INT NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `informacionAdicional` VARCHAR(200) NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATE NULL,
  `fechaDescargo` DATE NULL,
  `fechaRevision` DATE NULL,
  `idDependenciaRemision` INT NULL,
  `fechaRemision` DATE NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idEstadoPatronato` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaPatronato`),
  CONSTRAINT `FEP_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idEstadoPatronato_FK`
    FOREIGN KEY (`idEstadoPatronato`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idAsuntoPatronato_FK`
    FOREIGN KEY (`idAsuntoPatronato`)
    REFERENCES `AsuntoPatronato` (`idAsuntoPatronato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idDependenciaRemision_FK`
    FOREIGN KEY (`idDependenciaRemision`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FEP_idEmpleadoReceptor_FK_idx` ON `FichaEntradaPatronato` (`idEmpleadoReceptor` ASC) VISIBLE;

CREATE INDEX `FEP_idAbogadoAsignado_FK_idx` ON `FichaEntradaPatronato` (`idAbogadoAsignado` ASC) VISIBLE;

CREATE INDEX `FEP_idDictamen_FK_idx` ON `FichaEntradaPatronato` (`idDictamen` ASC) VISIBLE;

CREATE UNIQUE INDEX `idDictamen_UNIQUE` ON `FichaEntradaPatronato` (`idDictamen` ASC) VISIBLE;

CREATE INDEX `FEP_idEstadoPatronato_FK_idx` ON `FichaEntradaPatronato` (`idEstadoPatronato` ASC) VISIBLE;

CREATE INDEX `FEP_idAsuntoPatronato_FK_idx` ON `FichaEntradaPatronato` (`idAsuntoPatronato` ASC) VISIBLE;

CREATE INDEX `FEP_idDependenciaRemision_FK_idx` ON `FichaEntradaPatronato` (`idDependenciaRemision` ASC) VISIBLE;

CREATE INDEX `FEP_idProcedencia_FK_idx` ON `FichaEntradaPatronato` (`idProcedencia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaOpinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaOpinion` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaOpinion` (
  `idFichaEntradaOpinion` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `apoderadoLegal` VARCHAR(45) NULL,
  `asunto` VARCHAR(200) NOT NULL,
  `numOficio` VARCHAR(30) NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `informacionAdicional` VARCHAR(200) NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATE NULL,
  `fechaDescargo` DATE NULL,
  `fechaRevision` DATE NULL,
  `fechaRemision` DATE NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idEstadoOpinion` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaOpinion`),
  CONSTRAINT `FEO_idProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idEstadoOpinion_FK`
    FOREIGN KEY (`idEstadoOpinion`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FEO_idProcedencia_FK_idx` ON `FichaEntradaOpinion` (`idProcedencia` ASC) VISIBLE;

CREATE INDEX `FEO_idEmpleadoReceptor_FK_idx` ON `FichaEntradaOpinion` (`idEmpleadoReceptor` ASC) VISIBLE;

CREATE INDEX `FEO_idAbogadoAsignado_FK_idx` ON `FichaEntradaOpinion` (`idAbogadoAsignado` ASC) VISIBLE;

CREATE INDEX `FEO_idEstadoOpinion_idx` ON `FichaEntradaOpinion` (`idEstadoOpinion` ASC) VISIBLE;

CREATE INDEX `FEO_idDictamen_FK_idx` ON `FichaEntradaOpinion` (`idDictamen` ASC) VISIBLE;

CREATE UNIQUE INDEX `idDictamen_UNIQUE` ON `FichaEntradaOpinion` (`idDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaExpedienteXExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaExpedienteXExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaExpedienteXExpediente` (
  `idFichaEntradaExpediente` INT NOT NULL,
  `idExpediente` INT NOT NULL,
  PRIMARY KEY (`idFichaEntradaExpediente`, `idExpediente`),
  CONSTRAINT `FEEXE_idFichaEntradaExpediente_FK`
    FOREIGN KEY (`idFichaEntradaExpediente`)
    REFERENCES `FichaEntradaExpediente` (`idFichaEntradaExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FEEXE_idExpediente_FK`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `Expediente` (`idExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FEEXE_idExpediente_idx` ON `FichaEntradaExpedienteXExpediente` (`idExpediente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TipoComunidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoComunidad` ;

CREATE TABLE IF NOT EXISTS `TipoComunidad` (
  `idTipoComunidad` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoComunidad` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idTipoComunidad`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombreTipoPatronato_UNIQUE` ON `TipoComunidad` (`nombreTipoComunidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PdfDictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PdfDictamen` ;

CREATE TABLE IF NOT EXISTS `PdfDictamen` (
  `idPdfDictamen` INT NOT NULL AUTO_INCREMENT,
  `idDictamen` INT NOT NULL,
  `urlPdf` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPdfDictamen`),
  CONSTRAINT `PdfDictamen_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `PdfDictamen_idDictamen_FK_idx` ON `PdfDictamen` (`idDictamen` ASC) VISIBLE;

CREATE UNIQUE INDEX `urlPdfDictamen_UNIQUE` ON `PdfDictamen` (`urlPdf` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Privilegio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Privilegio` ;

CREATE TABLE IF NOT EXISTS `Privilegio` (
  `idPrivilegio` INT NOT NULL AUTO_INCREMENT,
  `nombrePrivilegio` VARCHAR(30) NOT NULL,
  `codigoPrivilegio` VARCHAR(6) NOT NULL,
  `descripcionPrivilegio` VARCHAR(70) NULL,
  PRIMARY KEY (`idPrivilegio`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombrePrivilegio_UNIQUE` ON `Privilegio` (`nombrePrivilegio` ASC) VISIBLE;

CREATE UNIQUE INDEX `codigoPrivilegio_UNIQUE` ON `Privilegio` (`codigoPrivilegio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `numEmpleado` INT NOT NULL,
  `identificacionUsuario` VARCHAR(26) NOT NULL,
  `password` CHAR(64) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `Usuario_numEmpleado_FK`
    FOREIGN KEY (`numEmpleado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Usuario_UNIQUE` ON `Usuario` (`numEmpleado` ASC) VISIBLE;

CREATE UNIQUE INDEX `identificacionUsuario_UNIQUE` ON `Usuario` (`identificacionUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PrivilegioXUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PrivilegioXUsuario` ;

CREATE TABLE IF NOT EXISTS `PrivilegioXUsuario` (
  `idPrivilegio` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPrivilegio`, `idUsuario`),
  CONSTRAINT `PrivilegioXUsuario_idUsuario_FK`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PrivilegioXUsuario_idPrivilegio`
    FOREIGN KEY (`idPrivilegio`)
    REFERENCES `Privilegio` (`idPrivilegio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `PrivilegioXUsuario_idUsuario_FK_idx` ON `PrivilegioXUsuario` (`idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Municipio` ;

CREATE TABLE IF NOT EXISTS `Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombreMunicipio` VARCHAR(45) NOT NULL,
  `codigoMunicipio` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idMunicipio`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `codigoMunicipio_UNIQUE` ON `Municipio` (`codigoMunicipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Comunidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comunidad` ;

CREATE TABLE IF NOT EXISTS `Comunidad` (
  `idComunidad` INT NOT NULL AUTO_INCREMENT,
  `nombreComunidad` VARCHAR(45) NOT NULL,
  `idMunicipio` INT NOT NULL,
  `idTipoComunidad` INT NOT NULL,
  PRIMARY KEY (`idComunidad`),
  CONSTRAINT `Comunidad_idMunicipio_FK`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Comunidad_idTipoComunidad_FK`
    FOREIGN KEY (`idTipoComunidad`)
    REFERENCES `TipoComunidad` (`idTipoComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Comunidad_idMunicipio_FK_idx` ON `Comunidad` (`idMunicipio` ASC) VISIBLE;

CREATE INDEX `Comunidad_idTipoComunidad_FK_idx` ON `Comunidad` (`idTipoComunidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ExpedientePatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExpedientePatronato` ;

CREATE TABLE IF NOT EXISTS `ExpedientePatronato` (
  `idExpedientePatronato` INT NOT NULL AUTO_INCREMENT,
  `idComunidadRelacionada` INT NOT NULL,
  `numExpedientePatronato` VARCHAR(30) NOT NULL,
  `folios` INT NOT NULL,
  PRIMARY KEY (`idExpedientePatronato`),
  CONSTRAINT `EP_idComunidadRelacionada_FK`
    FOREIGN KEY (`idComunidadRelacionada`)
    REFERENCES `Comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `EP_idComunidadRelacionada_FK_idx` ON `ExpedientePatronato` (`idComunidadRelacionada` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ArchivoAdjunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArchivoAdjunto` ;

CREATE TABLE IF NOT EXISTS `ArchivoAdjunto` (
  `idArchivoAdjunto` INT NOT NULL AUTO_INCREMENT,
  `idDictamen` INT NOT NULL,
  `urlArchivoAdjunto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idArchivoAdjunto`),
  CONSTRAINT `AA_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `urlArchivoAdjunto_UNIQUE` ON `ArchivoAdjunto` (`urlArchivoAdjunto` ASC) VISIBLE;

CREATE INDEX `AA_idDictamen_FK_idx` ON `ArchivoAdjunto` (`idDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaPatronatoXExpedientePatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaPatronatoXExpedientePatronato` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaPatronatoXExpedientePatronato` (
  `idFichaEntradaPatronato` INT NOT NULL,
  `idExpedientePatronato` INT NOT NULL,
  PRIMARY KEY (`idFichaEntradaPatronato`, `idExpedientePatronato`),
  CONSTRAINT `FEPXEP_idFichaEntradaPatronato_FK`
    FOREIGN KEY (`idFichaEntradaPatronato`)
    REFERENCES `FichaEntradaPatronato` (`idFichaEntradaPatronato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FEPXEP_idExpedientePatronato_FK`
    FOREIGN KEY (`idExpedientePatronato`)
    REFERENCES `ExpedientePatronato` (`idExpedientePatronato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FEPXEP_idExpedientePatronato_FK_idx` ON `FichaEntradaPatronatoXExpedientePatronato` (`idExpedientePatronato` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `WordDictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WordDictamen` ;

CREATE TABLE IF NOT EXISTS `WordDictamen` (
  `idWordDictamen` INT NOT NULL AUTO_INCREMENT,
  `idDictamen` INT NOT NULL,
  `urlWord` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idWordDictamen`),
  CONSTRAINT `WordDictamen_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `urlWord_UNIQUE` ON `WordDictamen` (`urlWord` ASC) VISIBLE;

CREATE INDEX `WordDictamen_idDictamen_FK_idx` ON `WordDictamen` (`idDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaOpinionXExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaOpinionXExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaOpinionXExpediente` (
  `idFichaEntradaOpinion` INT NOT NULL,
  `idExpediente` INT NOT NULL,
  PRIMARY KEY (`idFichaEntradaOpinion`, `idExpediente`),
  CONSTRAINT `FEOXE_idFichaEntradaOpinion_FK`
    FOREIGN KEY (`idFichaEntradaOpinion`)
    REFERENCES `FichaEntradaOpinion` (`idFichaEntradaOpinion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FEOXE_idExpediente_FK`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `Expediente` (`idExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FEOXE_idExpediente_FK_idx` ON `FichaEntradaOpinionXExpediente` (`idExpediente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
