-- MySQL Script generated by MySQL Workbench
-- Wed Aug  1 15:14:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE gerencialegal_amdc;
USE gerencialegal_amdc;
-- -----------------------------------------------------
-- Table `Dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dependencia` ;

CREATE TABLE IF NOT EXISTS `Dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `nombreDependencia` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idDependencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CargoEmpleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CargoEmpleado` ;

CREATE TABLE IF NOT EXISTS `CargoEmpleado` (
  `idCargoEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombreCargoEmpleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargoEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleado` ;

CREATE TABLE IF NOT EXISTS `Empleado` (
  `numEmpleado` INT NOT NULL,
  `nombresEmpleado` VARCHAR(40) NOT NULL,
  `apellidosEmpleado` VARCHAR(40) NOT NULL,
  `activo` TINYINT NOT NULL,
  `idCargo` INT NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`numEmpleado`),
  CONSTRAINT `Empleado_idCargo_FK`
    FOREIGN KEY (`idCargo`)
    REFERENCES `CargoEmpleado` (`idCargoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Empleado_idCargo_FK_idx` ON `Empleado` (`idCargo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EstadoExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EstadoExpediente` ;

CREATE TABLE IF NOT EXISTS `EstadoExpediente` (
  `idEstadoExpediente` INT NOT NULL AUTO_INCREMENT,
  `nombreEstadoExpediente` VARCHAR(45) NOT NULL,
  `descripciónEstadoExpedientecol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEstadoExpediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TipoDictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoDictamen` ;

CREATE TABLE IF NOT EXISTS `TipoDictamen` (
  `idTipoDictamen` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoDictamencol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDictamen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dictamen` ;

CREATE TABLE IF NOT EXISTS `Dictamen` (
  `idDictamen` INT NOT NULL AUTO_INCREMENT,
  `numDictamen` VARCHAR(25) NOT NULL,
  `idTipoDictamen` INT NOT NULL,
  PRIMARY KEY (`idDictamen`),
  CONSTRAINT `Dictamen_idTipoDictamen_FK`
    FOREIGN KEY (`idTipoDictamen`)
    REFERENCES `TipoDictamen` (`idTipoDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Dictamen_idTipoDictamen_FK_idx` ON `Dictamen` (`idTipoDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaExpediente` (
  `idFichaEntradaExpediente` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `interesado` VARCHAR(45) NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignación` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `idDependenciaRemision` INT NULL,
  `fechaRemision` DATETIME NULL,
  `idEstadoExpediente` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaExpediente`),
  CONSTRAINT `FEE_iProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idDependencia_FK`
    FOREIGN KEY (`idDependenciaRemision`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idEstadoExpediente_FK`
    FOREIGN KEY (`idEstadoExpediente`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1256;

CREATE INDEX `FEE_iProcedencia_FK_idx` ON `FichaEntradaExpediente` (`idProcedencia` ASC) VISIBLE;

CREATE INDEX `FEE_idEmpleadoReceptor_FK_idx` ON `FichaEntradaExpediente` (`idEmpleadoReceptor` ASC) VISIBLE;

CREATE INDEX `FEE_idAbogadoAsignado_FK_idx` ON `FichaEntradaExpediente` (`idAbogadoAsignado` ASC) VISIBLE;

CREATE INDEX `FEE_idDependencia_FK_idx` ON `FichaEntradaExpediente` (`idDependenciaRemision` ASC) VISIBLE;

CREATE INDEX `FEE_idEstadoExpediente_FK_idx` ON `FichaEntradaExpediente` (`idEstadoExpediente` ASC) VISIBLE;

CREATE INDEX `FEE_idDictamen_FK_idx` ON `FichaEntradaExpediente` (`idDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TipoExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoExpediente` ;

CREATE TABLE IF NOT EXISTS `TipoExpediente` (
  `idTipoExpediente` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoExpediente` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(150) NULL,
  PRIMARY KEY (`idTipoExpediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Expediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Expediente` ;

CREATE TABLE IF NOT EXISTS `Expediente` (
  `idExpediente` INT NOT NULL AUTO_INCREMENT,
  `numExpediente` VARCHAR(20) NOT NULL,
  `idTipoExpediente` INT NULL,
  `folios` INT NOT NULL,
  PRIMARY KEY (`idExpediente`),
  CONSTRAINT `Expediente_idTipoExpediente_FK`
    FOREIGN KEY (`idTipoExpediente`)
    REFERENCES `TipoExpediente` (`idTipoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `numExpediente_UNIQUE` ON `Expediente` (`numExpediente` ASC) VISIBLE;

CREATE INDEX `Expediente_idTipoExpediente_FK_idx` ON `Expediente` (`idTipoExpediente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RevisionExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RevisionExpediente` ;

CREATE TABLE IF NOT EXISTS `RevisionExpediente` (
  `idRevisionExpediente` INT NOT NULL AUTO_INCREMENT,
  `idFichaEntradaExpediente` INT NOT NULL,
  `idDependenciaRemison` INT NOT NULL,
  `fechaRemison` INT NOT NULL,
  `conDictamen` TINYINT NOT NULL,
  `idDependenciaRegreso` INT NULL,
  `fechaRegreso` DATETIME NULL,
  PRIMARY KEY (`idRevisionExpediente`),
  CONSTRAINT `RE_idFichaEntradaExpediente_FK`
    FOREIGN KEY (`idFichaEntradaExpediente`)
    REFERENCES `FichaEntradaExpediente` (`idFichaEntradaExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `RE_idDependenciaRemision_FK`
    FOREIGN KEY (`idDependenciaRemison`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RE_idDependenciaRegreso_FK`
    FOREIGN KEY (`idDependenciaRegreso`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `RE_idFichaEntradaExpediente_FK_idx` ON `RevisionExpediente` (`idFichaEntradaExpediente` ASC) VISIBLE;

CREATE INDEX `RE_idDependenciaRemision_FK_idx` ON `RevisionExpediente` (`idDependenciaRemison` ASC) VISIBLE;

CREATE INDEX `RE_idDependenciaRegreso_FK_idx` ON `RevisionExpediente` (`idDependenciaRegreso` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Folder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Folder` ;

CREATE TABLE IF NOT EXISTS `Folder` (
  `idFolder` INT NOT NULL AUTO_INCREMENT,
  `nombreFolder` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idFolder`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archivo` ;

CREATE TABLE IF NOT EXISTS `Archivo` (
  `idDictamen` INT NOT NULL,
  `idFolder` INT NOT NULL,
  PRIMARY KEY (`idDictamen`, `idFolder`),
  CONSTRAINT `Archivo_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Archivo_idFolder_FK`
    FOREIGN KEY (`idFolder`)
    REFERENCES `Folder` (`idFolder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Archivo_idFolder_FK_idx` ON `Archivo` (`idFolder` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TipoPatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoPatronato` ;

CREATE TABLE IF NOT EXISTS `TipoPatronato` (
  `idTipoPatronato` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoPatronato` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idTipoPatronato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FichaEntradaPatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaPatronato` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaPatronato` (
  `idFichaEntradaPatronato` INT NOT NULL AUTO_INCREMENT,
  `idTipoPatronato` INT NOT NULL,
  `nombreColonia` VARCHAR(45) NOT NULL,
  `Asunto` VARCHAR(60) NOT NULL,
  `folios` INT NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `fechaRemision` DATETIME NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaPatronato`),
  CONSTRAINT `FEP_idTipoPatronato_FK`
    FOREIGN KEY (`idTipoPatronato`)
    REFERENCES `TipoPatronato` (`idTipoPatronato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FEP_idTipoPatronato_FK_idx` ON `FichaEntradaPatronato` (`idTipoPatronato` ASC) VISIBLE;

CREATE INDEX `FEP_idEmpleadoReceptor_FK_idx` ON `FichaEntradaPatronato` (`idEmpleadoReceptor` ASC) VISIBLE;

CREATE INDEX `FEP_idAbogadoAsignado_FK_idx` ON `FichaEntradaPatronato` (`idAbogadoAsignado` ASC) VISIBLE;

CREATE INDEX `FEP_idDictamen_FK_idx` ON `FichaEntradaPatronato` (`idDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaOpinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaOpinion` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaOpinion` (
  `idFichaEntradaOpinion` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `numOficio` VARCHAR(30) NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `fechaRemision` DATETIME NULL,
  `idEstadoOpinion` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaOpinion`),
  CONSTRAINT `FEO_idProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idEstadoOpinion_FK`
    FOREIGN KEY (`idEstadoOpinion`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FEO_idProcedencia_FK_idx` ON `FichaEntradaOpinion` (`idProcedencia` ASC) VISIBLE;

CREATE INDEX `FEO_idEmpleadoReceptor_FK_idx` ON `FichaEntradaOpinion` (`idEmpleadoReceptor` ASC) VISIBLE;

CREATE INDEX `FEO_idAbogadoAsignado_FK_idx` ON `FichaEntradaOpinion` (`idAbogadoAsignado` ASC) VISIBLE;

CREATE INDEX `FEO_idEstadoOpinion_idx` ON `FichaEntradaOpinion` (`idEstadoOpinion` ASC) VISIBLE;

CREATE INDEX `FEO_idDictamen_FK_idx` ON `FichaEntradaOpinion` (`idDictamen` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FichaEntradaExpedienteXExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaExpedienteXExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaExpedienteXExpediente` (
  `idFichaEntradaExpediente` INT NOT NULL,
  `idExpediente` INT NOT NULL,
  PRIMARY KEY (`idFichaEntradaExpediente`, `idExpediente`),
  CONSTRAINT `FEEXE_idFichaEntradaExpediente_FK`
    FOREIGN KEY (`idFichaEntradaExpediente`)
    REFERENCES `FichaEntradaExpediente` (`idFichaEntradaExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FEEXE_idExpediente_FK`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `Expediente` (`idExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FEEXE_idExpediente_idx` ON `FichaEntradaExpedienteXExpediente` (`idExpediente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
