-- MySQL Script generated by MySQL Workbench
-- Tue Aug 14 09:26:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `gerencialegal_amdc` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `gerencialegal_amdc` DEFAULT CHARACTER SET utf8 ;
USE `gerencialegal_amdc` ;

-- -----------------------------------------------------
-- Table `Dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dependencia` ;

CREATE TABLE IF NOT EXISTS `Dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `nombreDependencia` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idDependencia`))
ENGINE = InnoDB;

ALTER TABLE `Dependencia` ADD UNIQUE `nombreDependencia_UNIQUE` (`nombreDependencia` ASC);


-- -----------------------------------------------------
-- Table `CargoEmpleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CargoEmpleado` ;

CREATE TABLE IF NOT EXISTS `CargoEmpleado` (
  `idCargoEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombreCargoEmpleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargoEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleado` ;

CREATE TABLE IF NOT EXISTS `Empleado` (
  `numEmpleado` INT NOT NULL,
  `nombresEmpleado` VARCHAR(40) NOT NULL,
  `apellidosEmpleado` VARCHAR(40) NOT NULL,
  `activo` TINYINT NOT NULL,
  `idCargo` INT NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`numEmpleado`),
  CONSTRAINT `Empleado_idCargo_FK`
    FOREIGN KEY (`idCargo`)
    REFERENCES `CargoEmpleado` (`idCargoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `Empleado` ADD INDEX `Empleado_idCargo_FK_idx` (`idCargo` ASC);


-- -----------------------------------------------------
-- Table `EstadoExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EstadoExpediente` ;

CREATE TABLE IF NOT EXISTS `EstadoExpediente` (
  `idEstadoExpediente` INT NOT NULL AUTO_INCREMENT,
  `nombreEstadoExpediente` VARCHAR(45) NOT NULL,
  `descripciónEstadoExpedientecol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEstadoExpediente`))
ENGINE = InnoDB;

ALTER TABLE `EstadoExpediente` ADD UNIQUE `nombreEstadoExpediente_UNIQUE` (`nombreEstadoExpediente` ASC);


-- -----------------------------------------------------
-- Table `TipoDictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoDictamen` ;

CREATE TABLE IF NOT EXISTS `TipoDictamen` (
  `idTipoDictamen` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoDictamencol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDictamen`))
ENGINE = InnoDB;

ALTER TABLE `TipoDictamen` ADD UNIQUE `nombreTipoDictamencol_UNIQUE` (`nombreTipoDictamencol` ASC);


-- -----------------------------------------------------
-- Table `Dictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dictamen` ;

CREATE TABLE IF NOT EXISTS `Dictamen` (
  `idDictamen` INT NOT NULL AUTO_INCREMENT,
  `numDictamen` VARCHAR(25) NOT NULL,
  `idTipoDictamen` INT NOT NULL,
  PRIMARY KEY (`idDictamen`),
  CONSTRAINT `Dictamen_idTipoDictamen_FK`
    FOREIGN KEY (`idTipoDictamen`)
    REFERENCES `TipoDictamen` (`idTipoDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `Dictamen` ADD INDEX `Dictamen_idTipoDictamen_FK_idx` (`idTipoDictamen` ASC);

ALTER TABLE `Dictamen` ADD UNIQUE `numDictamen_UNIQUE` (`numDictamen` ASC);


-- -----------------------------------------------------
-- Table `FichaEntradaExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaExpediente` (
  `idFichaEntradaExpediente` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `interesado` VARCHAR(45) NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignación` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `idDependenciaRemision` INT NULL,
  `fechaRemision` DATETIME NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idEstadoExpediente` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaExpediente`),
  CONSTRAINT `FEE_iProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idDependencia_FK`
    FOREIGN KEY (`idDependenciaRemision`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idEstadoExpediente_FK`
    FOREIGN KEY (`idEstadoExpediente`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEE_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1256;

ALTER TABLE `FichaEntradaExpediente` ADD INDEX `FEE_iProcedencia_FK_idx` (`idProcedencia` ASC);

ALTER TABLE `FichaEntradaExpediente` ADD INDEX `FEE_idEmpleadoReceptor_FK_idx` (`idEmpleadoReceptor` ASC);

ALTER TABLE `FichaEntradaExpediente` ADD INDEX `FEE_idAbogadoAsignado_FK_idx` (`idAbogadoAsignado` ASC);

ALTER TABLE `FichaEntradaExpediente` ADD INDEX `FEE_idDependencia_FK_idx` (`idDependenciaRemision` ASC);

ALTER TABLE `FichaEntradaExpediente` ADD INDEX `FEE_idEstadoExpediente_FK_idx` (`idEstadoExpediente` ASC);

ALTER TABLE `FichaEntradaExpediente` ADD INDEX `FEE_idDictamen_FK_idx` (`idDictamen` ASC);

ALTER TABLE `FichaEntradaExpediente` ADD UNIQUE `idDictamen_UNIQUE` (`idDictamen` ASC);


-- -----------------------------------------------------
-- Table `TipoExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoExpediente` ;

CREATE TABLE IF NOT EXISTS `TipoExpediente` (
  `idTipoExpediente` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoExpediente` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(150) NULL,
  PRIMARY KEY (`idTipoExpediente`))
ENGINE = InnoDB;

ALTER TABLE `TipoExpediente` ADD UNIQUE `nombreTipoExpediente_UNIQUE` (`nombreTipoExpediente` ASC);


-- -----------------------------------------------------
-- Table `Expediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Expediente` ;

CREATE TABLE IF NOT EXISTS `Expediente` (
  `idExpediente` INT NOT NULL AUTO_INCREMENT,
  `numExpediente` VARCHAR(20) NOT NULL,
  `idTipoExpediente` INT NULL,
  `folios` INT NOT NULL,
  PRIMARY KEY (`idExpediente`),
  CONSTRAINT `Expediente_idTipoExpediente_FK`
    FOREIGN KEY (`idTipoExpediente`)
    REFERENCES `TipoExpediente` (`idTipoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `Expediente` ADD UNIQUE `numExpediente_UNIQUE` (`numExpediente` ASC);

ALTER TABLE `Expediente` ADD INDEX `Expediente_idTipoExpediente_FK_idx` (`idTipoExpediente` ASC);


-- -----------------------------------------------------
-- Table `RevisionExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RevisionExpediente` ;

CREATE TABLE IF NOT EXISTS `RevisionExpediente` (
  `idRevisionExpediente` INT NOT NULL AUTO_INCREMENT,
  `idFichaEntradaExpediente` INT NOT NULL,
  `idDependenciaRemison` INT NOT NULL,
  `fechaRemison` INT NOT NULL,
  `conDictamen` TINYINT NOT NULL,
  `idDependenciaRegreso` INT NULL,
  `fechaRegreso` DATETIME NULL,
  PRIMARY KEY (`idRevisionExpediente`),
  CONSTRAINT `RE_idFichaEntradaExpediente_FK`
    FOREIGN KEY (`idFichaEntradaExpediente`)
    REFERENCES `FichaEntradaExpediente` (`idFichaEntradaExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `RE_idDependenciaRemision_FK`
    FOREIGN KEY (`idDependenciaRemison`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RE_idDependenciaRegreso_FK`
    FOREIGN KEY (`idDependenciaRegreso`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `RevisionExpediente` ADD INDEX `RE_idFichaEntradaExpediente_FK_idx` (`idFichaEntradaExpediente` ASC);

ALTER TABLE `RevisionExpediente` ADD INDEX `RE_idDependenciaRemision_FK_idx` (`idDependenciaRemison` ASC);

ALTER TABLE `RevisionExpediente` ADD INDEX `RE_idDependenciaRegreso_FK_idx` (`idDependenciaRegreso` ASC);


-- -----------------------------------------------------
-- Table `Folder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Folder` ;

CREATE TABLE IF NOT EXISTS `Folder` (
  `idFolder` INT NOT NULL AUTO_INCREMENT,
  `nombreFolder` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idFolder`))
ENGINE = InnoDB;

ALTER TABLE `Folder` ADD UNIQUE `nombreFolder_UNIQUE` (`nombreFolder` ASC);


-- -----------------------------------------------------
-- Table `Archivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archivo` ;

CREATE TABLE IF NOT EXISTS `Archivo` (
  `idDictamen` INT NOT NULL,
  `idFolder` INT NOT NULL,
  PRIMARY KEY (`idDictamen`, `idFolder`),
  CONSTRAINT `Archivo_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Archivo_idFolder_FK`
    FOREIGN KEY (`idFolder`)
    REFERENCES `Folder` (`idFolder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `Archivo` ADD INDEX `Archivo_idFolder_FK_idx` (`idFolder` ASC);


-- -----------------------------------------------------
-- Table `TipoPatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoPatronato` ;

CREATE TABLE IF NOT EXISTS `TipoPatronato` (
  `idTipoPatronato` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoPatronato` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idTipoPatronato`))
ENGINE = InnoDB;

ALTER TABLE `TipoPatronato` ADD UNIQUE `nombreTipoPatronato_UNIQUE` (`nombreTipoPatronato` ASC);


-- -----------------------------------------------------
-- Table `FichaEntradaPatronato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaPatronato` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaPatronato` (
  `idFichaEntradaPatronato` INT NOT NULL AUTO_INCREMENT,
  `idTipoPatronato` INT NOT NULL,
  `nombreColonia` VARCHAR(45) NOT NULL,
  `Asunto` VARCHAR(60) NOT NULL,
  `folios` INT NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `fechaRemision` DATETIME NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaPatronato`),
  CONSTRAINT `FEP_idTipoPatronato_FK`
    FOREIGN KEY (`idTipoPatronato`)
    REFERENCES `TipoPatronato` (`idTipoPatronato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEP_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `FichaEntradaPatronato` ADD INDEX `FEP_idTipoPatronato_FK_idx` (`idTipoPatronato` ASC);

ALTER TABLE `FichaEntradaPatronato` ADD INDEX `FEP_idEmpleadoReceptor_FK_idx` (`idEmpleadoReceptor` ASC);

ALTER TABLE `FichaEntradaPatronato` ADD INDEX `FEP_idAbogadoAsignado_FK_idx` (`idAbogadoAsignado` ASC);

ALTER TABLE `FichaEntradaPatronato` ADD INDEX `FEP_idDictamen_FK_idx` (`idDictamen` ASC);

ALTER TABLE `FichaEntradaPatronato` ADD UNIQUE `idDictamen_UNIQUE` (`idDictamen` ASC);


-- -----------------------------------------------------
-- Table `FichaEntradaOpinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaOpinion` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaOpinion` (
  `idFichaEntradaOpinion` INT NOT NULL AUTO_INCREMENT,
  `idProcedencia` INT NOT NULL,
  `numOficio` VARCHAR(30) NOT NULL,
  `idEmpleadoReceptor` INT NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `idAbogadoAsignado` INT NULL,
  `fechaAsignacion` DATETIME NULL,
  `fechaDescargo` DATETIME NULL,
  `fechaRemision` DATETIME NULL,
  `recibidoPor` VARCHAR(45) NULL,
  `idEstadoOpinion` INT NOT NULL,
  `idDictamen` INT NULL,
  PRIMARY KEY (`idFichaEntradaOpinion`),
  CONSTRAINT `FEO_idProcedencia_FK`
    FOREIGN KEY (`idProcedencia`)
    REFERENCES `Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idEmpleadoReceptor_FK`
    FOREIGN KEY (`idEmpleadoReceptor`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idAbogadoAsignado_FK`
    FOREIGN KEY (`idAbogadoAsignado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idEstadoOpinion_FK`
    FOREIGN KEY (`idEstadoOpinion`)
    REFERENCES `EstadoExpediente` (`idEstadoExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEO_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `FichaEntradaOpinion` ADD INDEX `FEO_idProcedencia_FK_idx` (`idProcedencia` ASC);

ALTER TABLE `FichaEntradaOpinion` ADD INDEX `FEO_idEmpleadoReceptor_FK_idx` (`idEmpleadoReceptor` ASC);

ALTER TABLE `FichaEntradaOpinion` ADD INDEX `FEO_idAbogadoAsignado_FK_idx` (`idAbogadoAsignado` ASC);

ALTER TABLE `FichaEntradaOpinion` ADD INDEX `FEO_idEstadoOpinion_idx` (`idEstadoOpinion` ASC);

ALTER TABLE `FichaEntradaOpinion` ADD INDEX `FEO_idDictamen_FK_idx` (`idDictamen` ASC);

ALTER TABLE `FichaEntradaOpinion` ADD UNIQUE `idDictamen_UNIQUE` (`idDictamen` ASC);


-- -----------------------------------------------------
-- Table `FichaEntradaExpedienteXExpediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FichaEntradaExpedienteXExpediente` ;

CREATE TABLE IF NOT EXISTS `FichaEntradaExpedienteXExpediente` (
  `idFichaEntradaExpediente` INT NOT NULL,
  `idExpediente` INT NOT NULL,
  PRIMARY KEY (`idFichaEntradaExpediente`, `idExpediente`),
  CONSTRAINT `FEEXE_idFichaEntradaExpediente_FK`
    FOREIGN KEY (`idFichaEntradaExpediente`)
    REFERENCES `FichaEntradaExpediente` (`idFichaEntradaExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FEEXE_idExpediente_FK`
    FOREIGN KEY (`idExpediente`)
    REFERENCES `Expediente` (`idExpediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

ALTER TABLE `FichaEntradaExpedienteXExpediente` ADD INDEX `FEEXE_idExpediente_idx` (`idExpediente` ASC);


-- -----------------------------------------------------
-- Table `PaginaDictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaginaDictamen` ;

CREATE TABLE IF NOT EXISTS `PaginaDictamen` (
  `idPaginaDictamen` INT NOT NULL AUTO_INCREMENT,
  `idDictamen` INT NOT NULL,
  `numeroPagina` INT NOT NULL,
  PRIMARY KEY (`idPaginaDictamen`),
  CONSTRAINT `PaginaDictamen_idDictamen_FK`
    FOREIGN KEY (`idDictamen`)
    REFERENCES `Dictamen` (`idDictamen`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

ALTER TABLE `PaginaDictamen` ADD INDEX `PaginaDictamen_idDictamen_FK_idx` (`idDictamen` ASC);


-- -----------------------------------------------------
-- Table `Privilegio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Privilegio` ;

CREATE TABLE IF NOT EXISTS `Privilegio` (
  `idPrivilegio` INT NOT NULL AUTO_INCREMENT,
  `nombrePrivilegio` VARCHAR(30) NOT NULL,
  `descripcionPrivilegio` VARCHAR(50) NULL,
  PRIMARY KEY (`idPrivilegio`))
ENGINE = InnoDB;

ALTER TABLE `Privilegio` ADD INDEX `nombrePrivilegio_UNIQUE` (`nombrePrivilegio` ASC);


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `numEmpleado` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `Usuario_numEmpleado_FK`
    FOREIGN KEY (`numEmpleado`)
    REFERENCES `Empleado` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `Usuario` ADD INDEX `Usuariocol_UNIQUE` (`numEmpleado` ASC);


-- -----------------------------------------------------
-- Table `PrivilegioXUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PrivilegioXUsuario` ;

CREATE TABLE IF NOT EXISTS `PrivilegioXUsuario` (
  `idPrivilegio` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPrivilegio`, `idUsuario`),
  CONSTRAINT `PrivilegioXUsuario_idUsuario_FK`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PrivilegioXUsuario_idPrivilegio`
    FOREIGN KEY (`idPrivilegio`)
    REFERENCES `Privilegio` (`idPrivilegio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

ALTER TABLE `PrivilegioXUsuario` ADD INDEX `PrivilegioXUsuario_idUsuario_FK_idx` (`idUsuario` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
